### ISSUE TITLE
Documenting usage in Windows

### ISSUE THREAD

**Issue by rzerres** [cecton/pure-rust-locales#3]
# Context
This crate seems to support cross platform localization for rust.
Thanks for the work.

But documentation is a bit week. Can you please provide a intended usage example?
My rust code is using the crate [locales] (https://docs.rs/locales/0.1.0/locales) that is working currently in unix/posix
based systems that provide the  `LANG` env.
It seems your `twine` crate is working almost the same way :)

I'd to use any of them in Windows environments. 

Thanks 
Ralf

**Comment by cecton** [comment]
:wave: hey @rzerres 

I just saw this message sorry.

The crate `pure-rust-locales` is nothing like `twine` or `locales`. It is a complete different beast and it is probably not what you are looking for.

`pure-rust-locales` is currently used in `chrono` and this is the only example I know of. **It is not meant to be used as an internationalization library.** It is meant to be used **by** internationalization libraries. This is because this is too low level and it doesn't provide a nice API.

I will try to improve the doc to explain that better.

Thanks
