### ISSUE TITLE
macro `locale_match` failed if item doens't exist in all mods

### ISSUE THREAD

**Issue by CfirTsabari** [cecton/pure-rust-locales#4]
calling this code:
```rust 
pure_rust_locales::locale_match!(locale => LC_ADDRESS::LANG_LIB)
```
will cause a failure since `LC_ADDRESS::LANG_LIB` doesn't exist in all mods. 
i.e.:
```
cannot find value `LANG_LIB` in module `$crate::ce_RU::LC_ADDRESS
```

**Comment by cecton** [comment]
hmm... that's unfortunate... :thinking: any idea how to improve this?

**Comment by CfirTsabari** [comment]
Actually, I have started thinking about it.
I came to the conclusion that this is not possible with a match. 
The only thing I could think of was too different from the current code.
The general direction is to add some code in the generation that will represent the locale as a `struct` and not a `mod`, and expose function by using traits.

**Comment by cecton** [comment]
Yeah I really can't see a solution either... (I mean with the current state of things)

I do not have a strong opinion on the current implementation so I would gladly welcome a huge PR if it brings value to the project. (Even re-writing my poor code generator would be very welcome.)

There is something utterly important that you must know about the current implementation though: I wanted the compiler to optimize away unused code. Every constant or function that is not used in the final binary (the user's binary) should (and must) be stripped by the compiler. This is because we don't want to store all the information for all the languages on every program.

One possible alternative would be to generate one feature for every language so the user can decide to pull them all or exclude part of them.

**Comment by CfirTsabari** [comment]
I think I am missing something, in the current code, how does the compiler can optimize the usage of code ? if the user binary uses the macro with a dynamic locale that means that all the locales should be in the binaries.

From my perspective the main usage of a localization crate would be to handle all the locales and not specific locales, I think that instead of providing a feature for each locale, we can provide 2 APIs, one for accessing all of the locales dynamically and one that will allow you to fetch only the locale you wish for.

**Comment by cecton** [comment]
> I think I am missing something, in the current code, how does the compiler can optimize the usage of code ? if the user binary uses the macro with a dynamic locale that means that all the locales should be in the binaries.

When using the macro it's true that you will pull one LC_ something for all the languages but not all the information of everything. There are a lot of information on those locale files: https://docs.rs/pure-rust-locales/0.5.6/pure_rust_locales/en_US/index.html

On Chrono I think only the time related things are pulled: https://github.com/chronotope/chrono/blob/main/src/format/locales.rs

> From my perspective the main usage of a localization crate would be to handle all the locales and not specific locales

I've badly expressed myself. It's just an idea.

I was more thinking of influencing the locales that are pulled. If chrono pulls pure-rust-locales without defining any features (language features), can the user (the crate who would pull chrono) pull pure-rust-locales and pull **only** the locales they need? You see what I mean? I think it's important that it is optimized because not all programs need all the locales all the time.

```toml
chrono = "0.4"
# restrict to only 2 locales
pure-rust-locales = { version = "0.5", features = ["en-us", "fr-fr"] }
```

Here chrono don't really care about which locale it is pulling. It doesn't know where its going to be used. But the final binary knows so it should be able to reduce the scope of what they need.

Don't forget that those locales could be used in embedded device or in WASM.

**Comment by CfirTsabari** [comment]
Ohh I think I got it.
but still, :
1. That means a massive match in your code.
2. I don't see a use case for adding a feature per locale, I do see a use case for a feature per Info (i.e. `LANG_LIB`), I do see a use case for a feature that will allow\block getting locales danymiclly that's way making sure that only locales that you referenced manually will be taken inside your binary.


I think I will try to do the following:
1. Introduce a new type of struct for each locale.
2. introduce a type(optional) will aggregate all locale.
3. introduce trait that will return this values.

i am hoping this is the right direction, I am guessing we will know when I will create the draft pr(will take some time I am a bit swamped) 🤞

**Comment by cecton** [comment]
That sounds great!! Thank you for taking up on such a huge task! :pray: 

Don't hesitate to rewrite things as you prefer, I have no feelings for my code. Beware though that the parsing of those files is quite peculiar (weird things going on!)

If you want there is this crate that has a formatter (CodeFormatter) that helps indent the code source: https://crates.io/crates/indenter ... but you could also use `quote` or whatever

**Comment by CfirTsabari** [comment]
hi,
just an update I have started working on this and I have now figured out that this will be even harder since not all locales have the same fields even under the same category.

i.e. `cy_GB` has `LC_ADDRESS::COUNTRY_ISBN` but `cv_RU` doesn't.
that being said I am not sure I will continue working on this issue :-(

**Comment by cecton** [comment]
haha yes I forgot about that issue!

Yes no worry, I understand...

Is this issue really blocking for the use of pure-rust-locales in your project? Or do you have a plan B?

**Comment by CfirTsabari** [comment]
Yea it is, I have ended up just doing some hardcoding with a todo to get back to it when I have some more time.

**Comment by cecton** [comment]
I'm looking at it now because I would like to add a function in chrono to get the first day of the week depending on the locale and I discovered a few interesting things:

1. I think some stuff like `FIRST_WEEKDAY` actually have a "default" value. In this case the default value is Sunday (1). After checking the files, I think the file `localedata/locales/i18n` is actually the template for all the rest.

   I notice those files have kind of inheritance mechanism. It looks like this in the file `copy "fr_FR"` but I also saw `copy "i18n"` here and there. But unfortunately not for `FIRST_WEEKDAY`.

2. There is another library we can generate the locales from: Perl's [DateTime](https://metacpan.org/dist/DateTime-Locale/view/lib/DateTime/Locale/zu_ZA.pod). That one might be more consistent and easier to parse.

So at least I have 2 new proposals to add on the table now:

1. We can implement some kind of "default" mechanism that will enforce the default from somewhere.
2. Rewrite the entire thing to use Perl's DateTime (which is probably based on glibc anyway).

**Comment by jeremija** [comment]
Hey guys, I took a stab at rewriting the code generator with three rules in mind `locale_match!` shouldn't fail when:

- a value is missing from specific locale , in which case we wrap the items in `Option`
- a whole section is missing frm certain locale, in which case we just add a whole section with all values set to `None`>
- the values have been parsed as i64 and string in different locales. We always convert the ints to string when a mismatch is found.

To solve this, I added a processing step that collects metadata ofor each value by section and ensures the types always match.

This is most likely a breaking change, but hopefully won't break anything in `chrono`.

**Comment by cecton** [comment]
I like the approach because it's simple so probably with the least unexpected behaviors.

Do we need to convert i64 to string? It is not possible to do it the other way around? Can you show me some values that are strings and others that are i64?

**Comment by jeremija** [comment]
> I like the approach because it's simple so probably with the least unexpected behaviors.

Thanks @cecton, appreciate it!

> Do we need to convert i64 to string? It is not possible to do it the other way around? Can you show me some values that are strings and others that are i64?

The implementation will currently only convert existing `i64` to `String` only when a non-integer type is found by the parser in one of the locales. One such example is `COUNTRY_ISBN`:

`af_ZA::LC_ADDRESS::COUNTRY_ISBN` has type `i64` with value `0`: 
`ak_GH::LC_ADDRESS::COUNTRY_ISBN` has type `i64` with value `9964`
`an_ES::LC_ADDRESS::COUNTRY_ISBN` has type `&str` with value `"978-84"`.

And then if you try to do `locale_match!` over, it will fail due to diverging types.

**Comment by cecton** [comment]
ah yeah I see the parser is doing it's best to identify the type for each value:

```
fn value<'a, E: ParseError<&'a str>>(
    i: &'a str,
    escape_char: char,
    comment_char: char,
) -> IResult<&'a str, Value, E> {
    preceded(
        |x| sp(x, escape_char, comment_char),
        alt((
            map_res(integer, |s| i64::from_str_radix(s, 10).map(Value::Integer)),
            map(|x| string(x, escape_char), Value::String),
            map(|x| parse_raw(x, escape_char, comment_char), Value::Raw),
        )),
    )(i)
}
```

so there is definitely nothing wrong about assuming str if in one place it's using string instead of number.

I think it's still good to parse numbers whenever possible because otherwise the library that will use  pure-rust-locales will have to do the parsing itself at runtime which is a waste. So I think your proposal is perfect :ok_hand:
